### ISSUE TITLE
How does the synchronization work?

### ISSUE THREAD

**Issue by stefanmerker** [benkuper/FlowtoysConnectBridge#2]
Hi,

i have some floytoys capsule v2 and a connect bridge from floytoys.
The bridge ist working with the app from floytoys, but i'm interested in developing my own application for my PC.
I already got an connection via BLE to the bridge.

My Question is: How does the synchronization work?
I understood, that you have to set die capslue in sync-mode (Page 5) and send the OSc package with "/sync".
But what happens now?
For the change of different modes/settings I know that I have to send "p [group] [page] ...."

How can I put the different capsules in different groups?
How do I use the "/stopsync" command?

I would be very happy if someone could give me some kind of workflow for a scenario like 2 times 2 capsules that should go into two different groups.

Yours sincerely
Stefan

**Comment by benkuper** [comment]
Hello,
Right now using the official bridge, there is no documented way to use from a computer. This repo is for experimental bridge, which doesn't have the same firmware.

That being said, you can contact flowtoys to ask for this, there is a way to use the flowtoys connect app on computer, or send OSC messages to the phone app

**Comment by stefanmerker** [comment]
Hi,

Thank you for the quick reply. I will try to get in contact with flowtoys.

Yours sincerely
Stefan
